// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP9TNTMrXP-x2HlcAwd6tnM68ehsWAecg',
    appId: '1:465916303838:web:bd3bf8034752a0c23d654f',
    messagingSenderId: '465916303838',
    projectId: 'techinitiator-b7f28',
    authDomain: 'techinitiator-b7f28.firebaseapp.com',
    storageBucket: 'techinitiator-b7f28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3Iyib77JVqMzNjPSNFcCt_J0QAGRxPuU',
    appId: '1:465916303838:android:51096bc184577c2b3d654f',
    messagingSenderId: '465916303838',
    projectId: 'techinitiator-b7f28',
    storageBucket: 'techinitiator-b7f28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzD0eKdycjOcq9TwnDhA72WOtAfFFv22w',
    appId: '1:465916303838:ios:ee0993620301e8873d654f',
    messagingSenderId: '465916303838',
    projectId: 'techinitiator-b7f28',
    storageBucket: 'techinitiator-b7f28.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzD0eKdycjOcq9TwnDhA72WOtAfFFv22w',
    appId: '1:465916303838:ios:ee0993620301e8873d654f',
    messagingSenderId: '465916303838',
    projectId: 'techinitiator-b7f28',
    storageBucket: 'techinitiator-b7f28.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP9TNTMrXP-x2HlcAwd6tnM68ehsWAecg',
    appId: '1:465916303838:web:949370e1a55ededa3d654f',
    messagingSenderId: '465916303838',
    projectId: 'techinitiator-b7f28',
    authDomain: 'techinitiator-b7f28.firebaseapp.com',
    storageBucket: 'techinitiator-b7f28.firebasestorage.app',
  );
}
